-- Juneuary: microseason schema (multi-city).
--
-- DESIGN:
--   - microseasons         = the CONCEPT (global, city-independent).
--                            "Spider Season" is one row, even if it manifests
--                            in Seattle, SF, and Portland.
--   - microseason_occurrences = the per-city MANIFESTATION (timing, temps,
--                            triggers, climate sensitivity, local flavor).
--                            One row per (microseason, city).
--   - microseason_overlaps = per-city pairs of occurrences that co-occur.
--   - precipitation_types  = global vocabulary. Intensities are universal;
--                            patterns scope to cities via precipitation_pattern_cities.
--
-- Source-of-truth is data/*.yaml + data/cities/*.yaml.
-- This DB is regenerated by scripts/build_db.py.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- Cities
-- ---------------------------------------------------------------------------
-- A "parent" city owns the microseason catalog (concepts, occurrences,
-- normals, overlaps) for itself AND for any child "grid" cities that
-- reference it via parent_city_id. Child cities have their own lat/lng
-- (different Open-Meteo grid cell, so their observations are independent)
-- but inherit the catalog wholesale: same microseason vocabulary,
-- different weather signal per grid cell.
CREATE TABLE IF NOT EXISTS cities (
    id              INTEGER PRIMARY KEY,
    slug            TEXT NOT NULL UNIQUE,   -- 'seattle', 'san_francisco'
    name            TEXT NOT NULL,
    latitude        REAL,
    longitude       REAL,
    parent_city_id  INTEGER REFERENCES cities(id),  -- NULL for catalog-owning cities
    notes           TEXT
);

-- catalog_city_id = parent if set, else self. Used by the views below so a
-- query for a child city returns the parent's occurrences and normals.
DROP VIEW IF EXISTS v_catalog_city;
CREATE VIEW v_catalog_city AS
SELECT
    c.id                                AS city_id,
    c.slug                              AS city_slug,
    c.name                              AS city_name,
    c.latitude, c.longitude,
    COALESCE(c.parent_city_id, c.id)    AS catalog_city_id
FROM cities c;

-- ---------------------------------------------------------------------------
-- Series (global): winter/spring/summer/fall/first_sun/low_sun/...
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS series (
    id              INTEGER PRIMARY KEY,
    key             TEXT NOT NULL UNIQUE,
    name            TEXT NOT NULL,
    description     TEXT,
    is_alternating  INTEGER NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------------
-- Microseasons: the CONCEPT. City-independent.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS microseasons (
    id                  INTEGER PRIMARY KEY,
    canonical_name      TEXT NOT NULL UNIQUE,
    slug                TEXT NOT NULL UNIQUE,

    -- calendar | series | triggered_event | constant
    -- | climate_disaster | sun_phenomenon
    category            TEXT NOT NULL CHECK (category IN (
                            'calendar','series','triggered_event',
                            'constant','climate_disaster','sun_phenomenon'
                        )),

    -- Series membership (concept-level: 'Fool''s Spring' IS spring1 everywhere
    -- it occurs; cities just decide whether to have an occurrence of it).
    series_id           INTEGER REFERENCES series(id),
    series_order        INTEGER,
    series_label        TEXT,                  -- 'spring1', 'winter2'

    description         TEXT,                  -- universal vibe/joke
    notes               TEXT
);

-- Aliases of the concept (e.g. Smaugust -> Smogust). Global.
CREATE TABLE IF NOT EXISTS microseason_aliases (
    microseason_id  INTEGER NOT NULL REFERENCES microseasons(id) ON DELETE CASCADE,
    alias           TEXT NOT NULL,
    PRIMARY KEY (microseason_id, alias)
);

-- ---------------------------------------------------------------------------
-- Microseason occurrences: per-city manifestation.
-- All weather thresholds, timing, climate-sensitivity flags live HERE
-- because they vary by city. Same concept can manifest differently.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS microseason_occurrences (
    id                      INTEGER PRIMARY KEY,
    microseason_id          INTEGER NOT NULL REFERENCES microseasons(id) ON DELETE CASCADE,
    city_id                 INTEGER NOT NULL REFERENCES cities(id) ON DELETE CASCADE,

    -- Timing (criterion 1)
    typical_start_month     INTEGER CHECK (typical_start_month BETWEEN 1 AND 12),
    typical_start_day       INTEGER CHECK (typical_start_day BETWEEN 1 AND 31),
    typical_end_month       INTEGER CHECK (typical_end_month BETWEEN 1 AND 12),
    typical_end_day         INTEGER CHECK (typical_end_day BETWEEN 1 AND 31),
    typical_duration_days   INTEGER,

    -- Thresholds (criterion 2)
    temp_min_f              REAL,
    temp_max_f              REAL,
    conditions_json         TEXT,              -- ["overcast","light_rain",...]

    -- Trigger combos (criterion 3)
    triggers                TEXT,

    -- Behavior (criteria 4 & 5)
    is_nonlinear            INTEGER NOT NULL DEFAULT 0,
    can_be_skipped          INTEGER NOT NULL DEFAULT 0,
    can_be_amplified        INTEGER NOT NULL DEFAULT 0,
    climate_drivers_json    TEXT,              -- ["heat_dome","wildfire",...]

    -- Optional local renames + local-flavor description.
    -- Default name is the concept's canonical_name; local_name overrides it
    -- ONLY for display in this city (e.g. a city that calls its smoke month
    -- something different).
    local_name              TEXT,
    local_description       TEXT,
    notes                   TEXT,

    UNIQUE (microseason_id, city_id)
);

-- ---------------------------------------------------------------------------
-- Overlaps: pairs of OCCURRENCES (per-city) that commonly co-occur.
-- (Spider Season∩Smoketember overlap dates differ between Seattle and SF,
--  so the relationship lives on the occurrence pair, not the concept pair.)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS microseason_overlaps (
    a_occurrence_id INTEGER NOT NULL REFERENCES microseason_occurrences(id) ON DELETE CASCADE,
    b_occurrence_id INTEGER NOT NULL REFERENCES microseason_occurrences(id) ON DELETE CASCADE,
    note            TEXT,
    PRIMARY KEY (a_occurrence_id, b_occurrence_id),
    CHECK (a_occurrence_id < b_occurrence_id)
    -- Same-city constraint enforced in the loader (SQLite can't reference
    -- another table's column in a CHECK).
);

-- ---------------------------------------------------------------------------
-- Precipitation taxonomy.
-- Intensities (Drizzling, Downpour, ...) are universal vocabulary.
-- Patterns (Pineapple Express, Convergence Zone, Karl the Fog) scope per-city.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS precipitation_types (
    id                          INTEGER PRIMARY KEY,
    canonical_name              TEXT NOT NULL UNIQUE,
    slug                        TEXT NOT NULL UNIQUE,
    kind                        TEXT NOT NULL CHECK (kind IN ('intensity','pattern')),
    intensity_rank              INTEGER,
    precip_rate_in_per_hr_min   REAL,
    precip_rate_in_per_hr_max   REAL,
    description                 TEXT,
    notes                       TEXT
);

-- Many-to-many: which cities each PATTERN applies to.
-- (Intensities are universal and don't appear here.)
CREATE TABLE IF NOT EXISTS precipitation_pattern_cities (
    precipitation_type_id   INTEGER NOT NULL REFERENCES precipitation_types(id) ON DELETE CASCADE,
    city_id                 INTEGER NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
    note                    TEXT,
    PRIMARY KEY (precipitation_type_id, city_id)
);

-- Per-occurrence rain types (future use; loader can populate from YAML).
CREATE TABLE IF NOT EXISTS occurrence_precipitation (
    occurrence_id           INTEGER NOT NULL REFERENCES microseason_occurrences(id) ON DELETE CASCADE,
    precipitation_type_id   INTEGER NOT NULL REFERENCES precipitation_types(id) ON DELETE CASCADE,
    PRIMARY KEY (occurrence_id, precipitation_type_id)
);

-- ---------------------------------------------------------------------------
-- Observations: one row per (city, date), sourced from Open-Meteo (or
-- manual). This is the ground truth that lets us track sequence
-- ("Fool's Spring last seen Feb 23, Second Winter started Mar 4") and
-- compute anomalies against city_climate_normals.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS observations (
    id                          INTEGER PRIMARY KEY,
    city_id                     INTEGER NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
    observed_date               TEXT NOT NULL,                         -- ISO YYYY-MM-DD
    source                      TEXT NOT NULL DEFAULT 'open_meteo',

    temp_high_f                 REAL,
    temp_low_f                  REAL,
    temp_mean_f                 REAL,
    precip_in                   REAL,
    snow_in                     REAL,
    cloud_cover_mean_pct        REAL,
    sun_hours                   REAL,

    smoke                       INTEGER NOT NULL DEFAULT 0,            -- 0/1
    pm25_ug_m3                  REAL,
    aqi_us                      REAL,

    solar_elevation_max_deg     REAL,                                  -- at solar noon

    -- Aberration flag. Set by the classifier when the observation is far
    -- enough from local normals to NOT count as evidence for a new
    -- microseason. A 95°F day in Seattle in January is real weather, but
    -- it's a fluke — we record the data, downgrade primary-match
    -- confidence, and suppress "propose new microseason" output.
    is_aberration               INTEGER NOT NULL DEFAULT 0,
    aberration_reason           TEXT,

    raw_json                    TEXT,                                   -- full API payload
    fetched_at                  TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE (city_id, observed_date, source)
);

CREATE INDEX IF NOT EXISTS idx_obs_city_date ON observations(city_id, observed_date);

-- Classifications attached to each observation. The `tier` column is what
-- makes Constants a "secondary forecast" — they ride alongside the primary
-- weather-of-the-day classification but aren't competing with it.
--
--   primary   - the weather classification(s) for this day (calendar/series/
--               climate_disaster). Usually 0–2 entries.
--   secondary - background traits currently active (constants like Spider
--               Season, Karl the Fog, Convergence Zones).
--   triggered - signal-driven events that fired today (Find Bananas, Praise
--               the Sun, Choking Smoke, etc.).
CREATE TABLE IF NOT EXISTS observation_microseasons (
    observation_id  INTEGER NOT NULL REFERENCES observations(id) ON DELETE CASCADE,
    occurrence_id   INTEGER NOT NULL REFERENCES microseason_occurrences(id) ON DELETE CASCADE,
    tier            TEXT NOT NULL CHECK (tier IN ('primary','secondary','triggered')),
    confidence      REAL,                                       -- 0..1
    reason          TEXT,                                       -- short explanation
    PRIMARY KEY (observation_id, occurrence_id, tier)
);

CREATE INDEX IF NOT EXISTS idx_obsm_occ ON observation_microseasons(occurrence_id);
CREATE INDEX IF NOT EXISTS idx_obsm_tier ON observation_microseasons(tier);

-- ---------------------------------------------------------------------------
-- View: for each city+microseason, the most recent date it was classified.
-- The basis for "what's the sequence so far this year?" displays.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS v_microseason_last_seen;
CREATE VIEW v_microseason_last_seen AS
SELECT
    c.slug                     AS city_slug,
    c.name                     AS city_name,
    m.canonical_name           AS canonical_name,
    COALESCE(occ.local_name, m.canonical_name) AS display_name,
    m.category                 AS category,
    m.series_label             AS series_label,
    om.tier                    AS tier,
    MIN(o.observed_date)       AS first_seen_date,
    MAX(o.observed_date)       AS last_seen_date,
    COUNT(*)                   AS days_observed
FROM observation_microseasons om
JOIN observations o            ON o.id   = om.observation_id
JOIN microseason_occurrences occ ON occ.id = om.occurrence_id
JOIN microseasons m            ON m.id   = occ.microseason_id
JOIN cities c                  ON c.id   = o.city_id
GROUP BY c.id, occ.id, om.tier;

-- ---------------------------------------------------------------------------
-- Historical climate normals per city.
--
-- Monthly granularity. Period is the source-of-record window
-- (e.g. NOAA NCEI 1991-2020 30-year normals).
--
-- The point of this table: each microseason's defining temperatures and
-- conditions are best understood as a DELTA from what's normal here for
-- this time of year. Fool's Spring isn't 60°F in absolute terms, it's
-- "+13°F over the February normal high in Seattle". Same observed
-- temperature in San Francisco is just February.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS city_climate_normals (
    city_id             INTEGER NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
    month               INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),

    -- Period of record + provenance
    period_start_year   INTEGER,
    period_end_year     INTEGER,
    source              TEXT,

    -- Temperature (°F). All averaged across the period.
    temp_max_avg_f      REAL,        -- avg of daily highs
    temp_min_avg_f      REAL,        -- avg of daily lows
    temp_mean_f         REAL,        -- daily mean

    -- Precipitation (inches)
    precip_total_in     REAL,        -- avg monthly total
    precip_days         REAL,        -- avg # of days with measurable precip
    snow_total_in       REAL,        -- avg monthly snowfall

    -- Sky / sun
    sun_pct             INTEGER,     -- avg % of possible sunshine
    cloud_cover_pct     INTEGER,     -- avg cloud cover

    -- Records (optional)
    temp_record_max_f   REAL,
    temp_record_min_f   REAL,

    PRIMARY KEY (city_id, month)
);

-- ---------------------------------------------------------------------------
-- View: occurrences + the climate normals for their START month.
-- A microseason's defining anomaly is computed against its start month.
-- Multi-month microseasons sit on a continuum; consumers can join to other
-- months from city_climate_normals directly if they need a span average.
--
-- Catalog-aware: each city_slug yields its catalog city's occurrences and
-- normals (parent if set, else self). Child cities see the parent's
-- catalog without duplicating any rows.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS v_occurrence_vs_normals;
CREATE VIEW v_occurrence_vs_normals AS
SELECT
    vc.city_slug                                        AS city_slug,
    vc.city_name                                        AS city_name,
    COALESCE(o.local_name, m.canonical_name)            AS display_name,
    m.canonical_name                                    AS canonical_name,
    m.category                                          AS category,
    o.typical_start_month                               AS start_month,
    o.temp_min_f, o.temp_max_f,
    n.temp_min_avg_f                                    AS normal_low_f,
    n.temp_max_avg_f                                    AS normal_high_f,
    n.precip_total_in                                   AS normal_precip_in,
    -- Anomalies (NULL if either side missing)
    CASE WHEN o.temp_max_f IS NOT NULL AND n.temp_max_avg_f IS NOT NULL
         THEN o.temp_max_f - n.temp_max_avg_f END       AS high_anomaly_f,
    CASE WHEN o.temp_min_f IS NOT NULL AND n.temp_min_avg_f IS NOT NULL
         THEN o.temp_min_f - n.temp_min_avg_f END       AS low_anomaly_f,
    o.id                                                AS occurrence_id,
    m.id                                                AS microseason_id
FROM v_catalog_city vc
JOIN microseason_occurrences o ON o.city_id = vc.catalog_city_id
JOIN microseasons m            ON m.id = o.microseason_id
LEFT JOIN city_climate_normals n
  ON n.city_id = vc.catalog_city_id AND n.month = o.typical_start_month;

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_occ_city            ON microseason_occurrences(city_id);
CREATE INDEX IF NOT EXISTS idx_occ_microseason     ON microseason_occurrences(microseason_id);
CREATE INDEX IF NOT EXISTS idx_occ_start_month     ON microseason_occurrences(typical_start_month);
CREATE INDEX IF NOT EXISTS idx_microseasons_cat    ON microseasons(category);
CREATE INDEX IF NOT EXISTS idx_microseasons_series ON microseasons(series_id, series_order);

-- ---------------------------------------------------------------------------
-- Convenience view: a flat "as-if-pre-refactor" listing per city.
--
-- Catalog-aware via v_catalog_city: each city_slug returns its catalog
-- city's occurrences (parent if set, else self). Child cities return
-- the parent's rows without storing duplicates.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS v_city_microseasons;
CREATE VIEW v_city_microseasons AS
SELECT
    vc.city_slug                                      AS city_slug,
    vc.city_name                                      AS city_name,
    m.id                                              AS microseason_id,
    o.id                                              AS occurrence_id,
    COALESCE(o.local_name, m.canonical_name)          AS display_name,
    m.canonical_name                                  AS canonical_name,
    m.category                                        AS category,
    s.key                                             AS series_key,
    m.series_order                                    AS series_order,
    m.series_label                                    AS series_label,
    o.typical_start_month, o.typical_start_day,
    o.typical_end_month,   o.typical_end_day,
    o.typical_duration_days,
    o.temp_min_f, o.temp_max_f,
    o.conditions_json,
    o.triggers,
    o.is_nonlinear, o.can_be_skipped, o.can_be_amplified,
    o.climate_drivers_json,
    m.description                                     AS concept_description,
    o.local_description                               AS local_description,
    o.notes                                           AS occurrence_notes
FROM v_catalog_city vc
JOIN microseason_occurrences o ON o.city_id = vc.catalog_city_id
JOIN microseasons m            ON m.id = o.microseason_id
LEFT JOIN series  s            ON s.id = m.series_id;
